apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: y1nmc7fz5-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:eefa3a4a6046426d38159a8abb1fa1509ca9f316@sha256:534ffa426d9c6383a5e3f3942d4ed7ea8c4fd86eee9a93e852341ebc0d3b4d87
          name: container-image
